
spring:
    application:
        name: dconnect-discord

    rabbitmq:
        password: guest
        username: guest
        host: localhost
        port: 5672

server:
    port: 8090

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
            default-zone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true

discord:
    bot:
        token: MTA0MTQwNTEyMjE3OTI0ODI1OQ.Gh6OwT.QtujUs48jBBJUPPw2Pygz27cVqz9NNme0fagQQ

feign:
    client:
        config:
            discord:
                connectTimeout: 100
                readTimeout: 100
                loggerLevel: basic
                retryer: feign.Retryer.Default
            infrastructure:
                connectTimeout: 100
                readTimeout: 100
                loggerLevel: basic
                retryer: feign.Retryer.Default

        discord:
            baseUrl: http://localhost:8090
        infrastructure:
            baseUrl: http://localhost:8091